name: reporting-backend

volumes:
  db-store:
  php-fpm-socket:

services:
  app:
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: reporting
      DB_USERNAME: reporting
      DB_PASSWORD: admin
      OCTANE_MAX_REQUEST: 1
    ports:
      - "8081:80"

  db:
    build: infrastructure/mysql
    volumes:
      - db-store:/var/lib/mysql:delegated
    ports:
      - "33307:3306"
    environment:
      MYSQL_DATABASE: reporting
      MYSQL_USER: reporting
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"